### ISSUE TITLE
Map demo about Biosamples needs schema update

### ISSUE THREAD

**Issue by marco-brandizi** [ktym/d3sparql#11]
Hi all, 

I hope this will reach you. I've been aware of D3SPARQL for a while and I appreciate you use our BioSD dataset for the map demo at http://biohackathon.org/d3sparql/. I'm filing this issue because we need to [change the OWL schema for such data](http://www.ebi.ac.uk/rdf/biosd/newschema16) and the changes will break the SPARQL you use for that example. 

[Here](http://goo.gl/ouWu2N) you can find an updated version of that query, changing the query on your side should be the only thing you need to do. In addition to following the new schema, the new query filters latitude/longitude labels via '=' operator, because that is faster than 'regex' and avoids dirty values associated to 'latitude and longitude'. You don't need to wait for our complete migration to make that change on D3SPARQL, since we are already publishing triples that are a mix of the old and new models.

I hope this bit of D3SPARQL will be updated because D3SPARQL is very good and I appreciate having BioSD listed as one of your examples. Please contact me if you need further help (brandizi A_T ebi AC UK/CO)

Kind Regards,
Marco.

**Comment by ktym** [comment]
Thank you! The SPARQL query is updated. Sorry to take long.

**Comment by marco-brandizi** [comment]
That's great! Thank you for developing D3SPARQL.
