### ISSUE TITLE
Being notified when new examples are added

### ISSUE THREAD

**Issue by ColinMaudry** [ktym/d3sparql#4]
Hello!

First of all, thanks for this great project, I plan to use it for several projects.

I would like to know if there is a way to subscribe and be notified when new viz examples are available (thus supported)?

I watch the project, but is there anything else?

Thanks!

**Comment by ktym** [comment]
Hi,

Thank you for your interest and valuable input. Because this is still a small project, we don't have community group / mailing list yet. Maybe I can prepare a README/ChangeLog file which summarizes major updates so that you will be notified by watching this project.

Cheers

**Comment by ColinMaudry** [comment]
A README would be great, thanks :) And I'll keep you updated with my use of d3sparql.
